POST http://localhost:7000/api/weeks/68aee42585a579ab4ba4a124
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlgtTGl2aXUiLCJpZCI6IjY4YWQ3ZjVmZTA3YTZlZDJmZjVlMGYzNiIsImlhdCI6MTc1NjQ1NDYwOCwiZXhwIjoxNzU3NjY0MjA4fQ.kBfd_TKLb5mLnVU9HWRHTA2Bv3UQ9FNccfLWT5KPl5w
Content-Type: application/json

{"name": "Friday"}
